### ISSUE TITLE
When Clicking a Notification it should highlight the notification

### ISSUE THREAD

**Issue by scottdensmore** [paxos/ghNotifier-issues#31] opened 2020-07-29 17:43 UTC
When you click the notification in Notification Center, it should highlight the notification (The Gif Doesn't show it) but when I did it, it just showed the window and didn't highlight the notification.

![2020-07-29 10 41 43](https://user-images.githubusercontent.com/125055/88834175-4add5c80-d188-11ea-895f-ebdab430fa31.gif)

**Comment by paxos** [comment] 2020-07-29 17:45
duplicate of https://github.com/paxos/ghNotifier-issues/issues/10

This annoys me like hell, so working on this very soon 👍

**Closed** 2020-07-31 07:06 UTC
